<?php
$id =$this->params()->fromQuery('id', '');
$p =$this->params()->fromQuery('p', 'item');
$item = $this->vars('item');
$site = $this->vars('site');

?>
<div class="container">
    <div class="row">
      <?php echo $this->partial('JDC/nav_tools',['item'=>$item,'heading'=>$this->vars('heading')]);?>
    </div>
    <div class="row">
      <div id='jdcGraph<?php echo $id;?>' class='jdc' ></div>
    </div>
</div>



<script>
  contDim = d3.select('#jdcGraph<?php echo $id;?>').node().getBoundingClientRect();    
  window.onload = function() { 
    oJDC = new jdc({'idCont':'jdcGraph<?php echo $id;?>','width':contDim.width,'height':600});
    toolTipAide = new jBox('Tooltip',{
      target: '#navItemJDCExistence',
      position: {
          x: 'center',
          y: 'top'
      },
      content:'Pour commencer créer ou sélectionner une existence'       
    }).open();
  };

</script>