<?php
$id =$this->params()->fromQuery('id', '');
$item = $id ? $this->api()->read('items',$id)->getContent() : false;
$site = $this->vars('site');

?>
<div class="container" id="jdcMainContainer">
    <div class="row">
      <?php //echo $this->partial('JDC/nav_tools',['item'=>$item,'heading'=>$this->vars('heading')]);?>
    </div>
    <div class="row">
      <div id='jdcGraph' class='jdc' ></div>
    </div>
</div>
<?php echo $this->partial('JDC/modal_ajoutRapport');?>
<?php echo $this->partial('JDC/modal_patienter');?>
<?php echo $this->partial('JDC/modal_creerDetail');?>

<script>
  item = <?php echo json_encode($item); ?>;

  window.onload = function() {
    initIhmJdc();
  };

</script>