<?php
$item = $this->vars('item');
$dim = $this->vars('dim');
$itemsDim = $this->api()->search('items',['resource_class_label'=>$dim])->getContent();
$itemsAsDim = $item ? $item->value('jdc:has'.$dim, ['all' => true]) : [];

$t = 1;

?>

<form class="px-4 py-3">
    <div class="mb-3" id='dimSelector<?php echo $dim;?>'>
        <?php foreach ($itemsDim as $i): ?>
        <div class="form-check" >
            <input type="checkbox" <?php echo itemChecked($itemsAsDim, $i);?>
            onchange='dimItemChange(<?php echo $this->json(['idDim'=>$i->id(),'idItem'=>($item ? $item->id() : 0),'dim'=>$dim]);?>)'
            class="form-check-input iss" id="ddcJDC<?php echo $i->id();?>">
            <label class="form-check-label" for="ddcJDC<?php echo $i->id();?>">
                <?php echo $i->displayTitle();?>
            </label>
            <i id='dimItemSpin<?php echo $i->id();?>' style='display:none' class="fas fa-cog fa-spin" ></i>
        </div>
        <?php endforeach; ?>
    </div>
</form>

