<div class="modal fade" id="modalCreerDetail" tabindex="-1" aria-labelledby="modalCreerDetailLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-fullscreen" >
        <div class="modal-content" style='background-color:black;'>
            <div class="modal-header">

            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Détailler une dimension">
                <div class="container-xl">
                <a class="navbar-brand" href="#">Détailler une dimension</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nbDetailDim" aria-controls="nbDetailDim" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="nbDetailDim">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" id='btnAssoTxt' href="#">Associer</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id='btnDissoTxt' href="#">Dissocier</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id='btnCateTxt' href="#">Catégoriser</a>
                    </li>
                    </ul>
                </div>
                </div>
            </nav>

            </div>
            <div class="modal-body" id="modalCreerDetailBody">
                <div class="container">
                    <div class="row">
                        <div id="modalCreerDetailTextTree" class="col">
                        </div>
                    </div>
                    <div class="row">
                        <?php echo $this->partial('JDC/nav_skos');?>
                    </div>
                    <div class="row">
                        <div id="modalCreerDetailExploskos" class="col">
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                <button type="button" id="btnSaveDetail" class="btn btn-primary">Enregistrer</button>
            </div>
        </div>
    </div>
</div>
