<div class="modal fade" id="modalAjoutRapport" tabindex="-1" aria-labelledby="modalAjoutRapportLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalAjoutRapportLabel">Ajouter un rapport</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="form-floating">
                    <select class="form-select" id="choixSujet" aria-label="Choix d'un sujet dans les dimensions de l'existence">
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <label for="choixSujet">Choisir un sujet</label>
                </div>
                <div class="form-floating">
                    <select class="form-select" id="choixObjet" aria-label="Choix d'un objet dans les dimensions de l'existence">
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <label for="choixObjet">Choisir un objet</label>
                </div>
                <div class="form-floating">
                    <select class="form-select" id="choixPredicat" aria-label="Choix d'un prédicat dans les dimensions de l'existence">
                        <option value="1">One</option>
                        <option value="2">Two</option>
                        <option value="3">Three</option>
                    </select>
                    <label for="choixSujet">Choisir un prédicat</label>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <button type="button" class="btn btn-primary">Ajouter</button>
            </div>
        </div>
    </div>
</div>