<div class="modal fade" id="modalPatienter" tabindex="-1" aria-labelledby="modalPatienterLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalPatienterLabel">Merci de patienter</h5>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
            <div class="progress">
                <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                </div>
            </div>
        </div>
    </div>
</div>