
<div id="contCptRapports" style='display:none;color:white' class="container">
        <div class="row">
                <h5 id="ajoutConceptLabel"></h5>
        </div>
        <div class="row">
                <div class="col-sm">
                        <div class="ui-widget">
                                <label style='color:white;' for="autocomplete_Physique">Sélectionner / Ajouter
                                        un physique :</label>
                                <div id="spin-autocomplete_Physique" style="display:none;color:white"
                                        class="spinner-border spinner-border-sm"
                                        role="status">
                                        <span class="sr-only">Chargement...</span>
                                </div>
                                <input class="form-control" id="autocomplete_Physique" size="64">
                                <button id="autocomplete_Physique_btnAjout" class="btn btn-primary" type="button">Ajouter</button>
                        </div>
                </div>
                <div class="col-sm">
                        <div class="ui-widget">
                                <label style='color:white;' for="autocomplete_Actant">Sélectionner / Ajouter
                                        un actant :</label>
                                <div id="spin-autocomplete_Actant" style="display:none;color:white"
                                        class="spinner-border spinner-border-sm"
                                        role="status">
                                        <span class="sr-only">Chargement...</span>
                                </div>
                                <input class="form-control" id="autocomplete_Actant" size="64">
                                <button id="autocomplete_Actant_btnAjout" class="btn btn-primary" type="button">Ajouter</button>
                        </div>
                </div>
                <div class="col-sm">
                        <div class="ui-widget">
                                <label style='color:white;' for="autocomplete_Concept">Sélectionner / Ajouter
                                        un concept :</label>
                                <div id="spin-autocomplete_Concept" style="display:none;color:white"
                                        class="spinner-border spinner-border-sm"
                                        role="status">
                                        <span class="sr-only">Chargement...</span>
                                </div>
                                <input class="form-control" id="autocomplete_Concept" size="64">
                                <button id="autocomplete_Concept_btnAjout" class="btn btn-primary" type="button">Ajouter</button>
                        </div>
                </div>
        </div>
        <div class="row">
                <div class="col-sm" id='contAddCptRapports'>
                        <div class="dropdown-divider"></div>
                </div>
        </div>


        <div class="row">

        <table class="table table-dark table-striped">
  <thead>
    <tr>
        <th scope="col"><i class="fas fa-plus-circle" onclick="ajoutRowRapport()"></i></th>
        <th scope="col">Sujet</th>
        <th scope="col">Prédicat</th>
        <th scope="col">Objet</th>
    </tr>
  </thead>
  <tbody id='tableAjoutRapport'>
  </tbody>
</table>

</div>

        <div class="row">
                <a href="#" class="btn btn-dark disabled" tabindex="-1" role="button"
                id="btnValiderAjoutSkos" aria-disabled="true">Valider</a>
        </div>
</div>
